# Source - https://stackoverflow.com/q
# Posted by Jotter Kain, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-25, License - CC BY-SA 4.0

services:
  db:
    container_name: postgres_orderService
    image: postgres:16.0
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=order_service
    volumes:
      - ./postgresql:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app


  kafka:
    container_name: kafka_orderService
    image: apache/kafka:4.0.1
    networks:
      - app
    ports:
      - "${KAFKA_PORT}:9092"



networks:
  app:
    driver: bridge

